import json
import os

SCHEMES_PATH = os.path.join(os.path.dirname(__file__), "schemes.json")

STATES = [
    ("Andhra Pradesh", "andhra pradesh", "आंध्र प्रदेश"),
    ("Arunachal Pradesh", "arunachal pradesh", "अरुणाचल प्रदेश"),
    ("Assam", "assam", "असम"),
    ("Bihar", "bihar", "बिहार"),
    ("Chhattisgarh", "chhattisgarh", "छत्तीसगढ़"),
    ("Goa", "goa", "गोवा"),
    ("Gujarat", "gujarat", "गुजरात"),
    ("Haryana", "haryana", "हरियाणा"),
    ("Himachal Pradesh", "himachal pradesh", "हिमाचल प्रदेश"),
    ("Jharkhand", "jharkhand", "झारखंड"),
    ("Karnataka", "karnataka", "कर्नाटक"),
    ("Kerala", "kerala", "केरल"),
    ("Madhya Pradesh", "madhya pradesh", "मध्य प्रदेश"),
    ("Maharashtra", "maharashtra", "महाराष्ट्र"),
    ("Manipur", "manipur", "मणिपुर"),
    ("Meghalaya", "meghalaya", "मेघालय"),
    ("Mizoram", "mizoram", "मिजोरम"),
    ("Nagaland", "nagaland", "नागालैंड"),
    ("Odisha", "odisha", "ओडिशा"),
    ("Punjab", "punjab", "पंजाब"),
    ("Rajasthan", "rajasthan", "राजस्थान"),
    ("Sikkim", "sikkim", "सिक्किम"),
    ("Tamil Nadu", "tamil nadu", "तमिलनाडु"),
    ("Telangana", "telangana", "तेलंगाना"),
    ("Tripura", "tripura", "त्रिपुरा"),
    ("Uttar Pradesh", "uttar pradesh", "उत्तर प्रदेश"),
    ("Uttarakhand", "uttarakhand", "उत्तराखंड"),
    ("West Bengal", "west bengal", "पश्चिम बंगाल"),
    ("Delhi", "delhi", "दिल्ली"),
    ("Jammu and Kashmir", "jammu and kashmir", "जम्मू और कश्मीर")
]

EDU_THEMES = [
    ("STEM Education", "स्टेम शिक्षा (विज्ञान, प्रौद्योगिकी, इंजीनियरिंग और गणित)", "science_technology"),
    ("Arts and Humanities", "कला और मानविकी", "arts"),
    ("Sports Excellence", "खेल उत्कृष्टता", "sports"),
    ("Differently-Abled Support", "दिव्यांग सहायता", "disability"),
    ("Minority Girls Education", "अल्पसंख्यक बालिका शिक्षा", "minority"),
    ("Digital Literacy", "डिजिटल साक्षरता", "digital"),
    ("Vocational Training", "व्यावसायिक प्रशिक्षण", "vocational"),
    ("Advanced Research", "उन्नत अनुसंधान", "research"),
    ("Distance Learning", "दूरस्थ शिक्षा", "distance_learning"),
    ("Linguistics and Classical Languages", "भाषा विज्ञान और शास्त्रीय भाषाएं", "linguistics"),
    ("Agricultural Sciences", "कृषि विज्ञान", "agriculture_edu"),
    ("Medical & Nursing", "चिकित्सा और नर्सिंग", "medical"),
    ("Law and Legal Studies", "कानून और कानूनी अध्ययन", "law"),
    ("Environmental Science", "पर्यावरण विज्ञान", "environment"),
    ("Fine Arts and Design", "ललित कला और डिजाइन", "fine_arts")
]

new_schemes = []

# 1. State-level Education Schemes for BPL / EWS (30 states * 6 templates = 180 schemes)
for s_name, s_id, s_hi in STATES:
    new_schemes.extend([
        {
            "id": f"{s_id.replace(' ','-')}-free-laptop-bpl",
            "name": f"{s_name} Free Laptop/Tablet Scheme for BPL Students",
            "shortName": f"{s_name} Free Laptop",
            "category": "education",
            "icon": "💻",
            "benefit": f"Free laptop or tablet for BPL students scoring above 75% in Class 10/12 in {s_name}",
            "benefitValue": 25000,
            "simpleExplanation": f"To bridge the digital divide, {s_name} provides free digital devices to meritorious students from economically weaker sections to assist in higher education.",
            "eligibility": {"minAge": 15, "maxAge": 22, "maxIncome": 150000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": [s_id], "conditions": ["student"]},
            "howToApply": ["Apply through the school principal", "Submit marksheet and BPL certificate", "Merit list published by state education board"],
            "documentsRequired": ["Aadhaar", "Class 10/12 Marksheet", "BPL Ration Card", "School ID"],
            "officialUrl": "https://education.gov.in",
            "whyQualifyTemplate": f"As a deserving student from a financially weak background in {s_name}, you can get a free laptop.",
            "nameHi": f"{s_hi} बीपीएल छात्रों के लिए मुफ्त लैपटॉप/टैबलेट योजना",
            "shortNameHi": f"{s_hi} मुफ्त लैपटॉप",
            "benefitHi": f"{s_hi} में कक्षा 10/12 में 75% से ऊपर अंक प्राप्त करने वाले बीपीएल छात्रों के लिए मुफ्त लैपटॉप या टैबलेट",
            "simpleExplanationHi": f"डिजिटल विभाजन को पाटने के लिए, {s_hi} आर्थिक रूप से कमजोर वर्गों के मेधावी छात्रों को उच्च शिक्षा में सहायता के लिए मुफ्त डिजिटल उपकरण प्रदान करता है।",
            "documentsRequiredHi": ["आधार", "कक्षा 10/12 की मार्कशीट", "बीपीएल राशन कार्ड", "स्कूल आईडी"],
            "howToApplyHi": ["स्कूल प्रिंसिपल के माध्यम से आवेदन करें", "मार्कशीट और बीपीएल प्रमाणपत्र जमा करें", "राज्य शिक्षा बोर्ड द्वारा प्रकाशित मेरिट सूची"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-residential-ews",
            "name": f"{s_name} EWS Boarding School Scholarship",
            "shortName": f"{s_name} EWS Boarding",
            "category": "education",
            "icon": "🏫",
            "benefit": f"100% free residential schooling for talented poor children across {s_name}",
            "benefitValue": 50000,
            "simpleExplanation": f"{s_name} pays for the full tuition, boarding, lodging, and books for exceptional students from Below Poverty Line families in premier residential schools.",
            "eligibility": {"minAge": 10, "maxAge": 18, "maxIncome": 100000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": [s_id], "conditions": ["student"]},
            "howToApply": ["Appear for the state-level selection test for EWS students", "Clear document verification", "Get admission letter"],
            "documentsRequired": ["Income Certificate", "Previous Class Marksheet", "Caste Certificate (if applicable)"],
            "officialUrl": "https://education.gov.in",
            "whyQualifyTemplate": f"Brilliant students from low-income families in {s_name} can secure high-quality residential education free of cost.",
            "nameHi": f"{s_hi} ईडब्ल्यूएस बोर्डिंग स्कूल छात्रवृत्ति",
            "shortNameHi": f"{s_hi} ईडब्ल्यूएस बोर्डिंग",
            "benefitHi": f"पूरे {s_hi} में प्रतिभाशाली गरीब बच्चों के लिए 100% मुफ्त आवासीय स्कूली शिक्षा",
            "simpleExplanationHi": f"{s_hi} प्रमुख आवासीय स्कूलों में गरीबी रेखा से नीचे के परिवारों के असाधारण छात्रों के लिए पूर्ण ट्यूशन, बोर्डिंग, आवास और पुस्तकों का भुगतान करता है।",
            "documentsRequiredHi": ["आय प्रमाण पत्र", "पिछली कक्षा की मार्कशीट", "जाति प्रमाण पत्र (यदि लागू हो)"],
            "howToApplyHi": ["ईडब्ल्यूएस छात्रों के लिए राज्य स्तरीय चयन परीक्षा में शामिल हों", "दस्तावेज़ सत्यापन स्पष्ट करें", "प्रवेश पत्र प्राप्त करें"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-free-coaching-bpl",
            "name": f"{s_name} Free Coaching for Competitive Exams (EWS)",
            "shortName": f"{s_name} Free Coaching",
            "category": "education",
            "icon": "📚",
            "benefit": f"Free coaching for JEE, NEET, UPSC, and State PSCs for EWS students in {s_name}",
            "benefitValue": 75000,
            "simpleExplanation": f"Don't let poverty stop your ambitions. The {s_name} government offers free enrollment in top coaching institutes along with a monthly stipend for boarding.",
            "eligibility": {"minAge": 16, "maxAge": 30, "maxIncome": 250000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student", "unemployed"], "states": [s_id], "conditions": ["student"]},
            "howToApply": ["Apply on the state coaching portal", "Take the screening test", "Select empirical coaching center from the list"],
            "documentsRequired": ["Aadhaar", "Income Certificate", "Educational Certificates"],
            "officialUrl": "https://socialjustice.gov.in",
            "whyQualifyTemplate": f"Prepare for major competitive exams for free under the {s_name} scheme.",
            "nameHi": f"{s_hi} प्रतियोगी परीक्षाओं के लिए मुफ्त कोचिंग (ईडब्ल्यूएस)",
            "shortNameHi": f"{s_hi} मुफ्त कोचिंग",
            "benefitHi": f"{s_hi} में ईडब्ल्यूएस छात्रों के लिए जेईई, एनईईटी, यूपीएससी और राज्य पीएससी के लिए मुफ्त कोचिंग",
            "simpleExplanationHi": f"गरीबी को अपनी महत्वाकांक्षाओं को रोकने न दें। {s_hi} सरकार बोर्डिंग के लिए मासिक वजीफे के साथ शीर्ष कोचिंग संस्थानों में मुफ्त नामांकन प्रदान करती है।",
            "documentsRequiredHi": ["आधार", "आय प्रमाण पत्र", "शैक्षिक प्रमाण पत्र"],
            "howToApplyHi": ["राज्य कोचिंग पोर्टल पर आवेदन करें", "स्क्रीनिंग टेस्ट दें", "सूची से अनुभवजन्य कोचिंग सेंटर का चयन करें"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-zero-interest-edu-loan",
            "name": f"{s_name} Higher Education Zero Interest Loan",
            "shortName": f"{s_name} Zero Interest Edu",
            "category": "education",
            "icon": "💳",
            "benefit": f"100% interest subvention on education loans for BPL students pursuing degrees in {s_name}",
            "benefitValue": 100000,
            "simpleExplanation": f"The {s_name} government pays the entire interest on education loans taken by students from poor backgrounds until they finish their graduation and secure a job.",
            "eligibility": {"minAge": 17, "maxAge": 25, "maxIncome": 450000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": [s_id], "conditions": ["student"]},
            "howToApply": ["Apply for an education loan in a scheduled bank", "Submit the interest waiver application via state portal", "Submit college bonafide certificate annually"],
            "documentsRequired": ["Bank Loan Sanction Letter", "College Admission Proof", "Income Certificate"],
            "officialUrl": "https://education.gov.in",
            "whyQualifyTemplate": f"Students in {s_name} can fund their higher education purely on the principal amount without interest burden.",
            "nameHi": f"{s_hi} उच्च शिक्षा शून्य ब्याज ऋण",
            "shortNameHi": f"{s_hi} शून्य ब्याज शिक्षा",
            "benefitHi": f"{s_hi} में डिग्री हासिल करने वाले बीपीएल छात्रों के लिए शिक्षा ऋण पर 100% ब्याज सहायता",
            "simpleExplanationHi": f"{s_hi} सरकार गरीब पृष्ठभूमि के छात्रों द्वारा लिए गए शिक्षा ऋण पर पूरा ब्याज तब तक चुकाती है जब तक वे अपना स्नातक पूरा नहीं कर लेते और नौकरी सुरक्षित नहीं कर लेते।",
            "documentsRequiredHi": ["बैंक ऋण स्वीकृति पत्र", "कॉलेज प्रवेश प्रमाण", "आय प्रमाण पत्र"],
            "howToApplyHi": ["अनुसूचित बैंक में शिक्षा ऋण के लिए आवेदन करें", "राज्य पोर्टल के माध्यम से ब्याज छूट आवेदन जमा करें", "सालाना कॉलेज वास्तविक प्रमाण पत्र जमा करें"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-school-uniform-bpl",
            "name": f"{s_name} Vidyarthi Suraksha & Uniform Top-Up",
            "shortName": f"{s_name} Free Uniforms",
            "category": "education",
            "icon": "👕",
            "benefit": f"₹2,000 yearly for uniforms, shoes, and bags for poor children in Govt schools in {s_name}",
            "benefitValue": 2000,
            "simpleExplanation": f"Direct Benefit Transfer (DBT) directly to the mothers' bank accounts to buy winter wear, uniforms, and study materials for children going to government schools.",
            "eligibility": {"minAge": 5, "maxAge": 15, "maxIncome": 200000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": [s_id], "conditions": ["student"]},
            "howToApply": ["Register student details in the state school database via the teacher", "Link mother's Aadhaar with bank account", "Receive cash annually"],
            "documentsRequired": ["Student Aadhaar", "Mother's Aadhaar", "Bank Account Details linked to NPCI"],
            "officialUrl": "https://education.gov.in",
            "whyQualifyTemplate": f"Ensure your child in {s_name} has all necessary school supplies via this DBT grant.",
            "nameHi": f"{s_hi} विद्यार्थी सुरक्षा और वर्दी टॉप-अप",
            "shortNameHi": f"{s_hi} मुफ्त वर्दी",
            "benefitHi": f"{s_hi} के सरकारी स्कूलों में गरीब बच्चों के लिए वर्दी, जूते और बैग के लिए सालाना ₹2,000",
            "simpleExplanationHi": f"सरकारी स्कूलों में जाने वाले बच्चों के लिए सर्दियों के कपड़े, वर्दी और अध्ययन सामग्री खरीदने के लिए सीधे माताओं के बैंक खातों में प्रत्यक्ष लाभ हस्तांतरण (DBT)।",
            "documentsRequiredHi": ["छात्र का आधार", "माता का आधार", "NPCI से जुड़ा बैंक खाता विवरण"],
            "howToApplyHi": ["शिक्षक के माध्यम से राज्य स्कूल डेटाबेस में छात्र विवरण दर्ज करें", "माता के आधार को बैंक खाते से लिंक करें", "सालाना नकद प्राप्त करें"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-girl-child-bpl-edu",
            "name": f"{s_name} BPL Kanya Shiksha Protsahan",
            "shortName": f"{s_name} BPL Girl Edu",
            "category": "education",
            "icon": "👧",
            "benefit": f"Fixed deposit of ₹50,000 for BPL families' daughter upon completing Class 12 in {s_name}",
            "benefitValue": 50000,
            "simpleExplanation": f"To prevent early marriages and encourage higher education, {s_name} awards a substantial cash incentive when a girl from a BPL family completes her schooling un-married.",
            "eligibility": {"minAge": 17, "maxAge": 19, "maxIncome": 100000, "categories": ["general", "obc", "sc", "st"], "gender": ["female"], "occupations": ["student"], "states": [s_id], "conditions": ["student"]},
            "howToApply": ["Enroll in Anganwadi/School tracking system", "Apply after passing Class 12 board exams", "Submit unmarried declaration"],
            "documentsRequired": ["Class 12 Marksheet", "BPL Certificate", "Age Proof", "Unmarried Declaration signed by Panchayat"],
            "officialUrl": "https://wcd.nic.in",
            "whyQualifyTemplate": f"As a female student completing school in {s_name}, you qualify for this maturity incentive.",
            "nameHi": f"{s_hi} बीपीएल कन्या शिक्षा प्रोत्साहन",
            "shortNameHi": f"{s_hi} बीपीएल बालिका शिक्षा",
            "benefitHi": f"{s_hi} में कक्षा 12 पूरी करने पर बीपीएल परिवारों की बेटी के लिए ₹50,000 की सावधि जमा",
            "simpleExplanationHi": f"जल्दी शादी को रोकने और उच्च शिक्षा को प्रोत्साहित करने के लिए, {s_hi} बीपीएल परिवार की लड़की के अविवाहित स्कूली शिक्षा पूरी करने पर पर्याप्त नकद प्रोत्साहन प्रदान करता है।",
            "documentsRequiredHi": ["कक्षा 12 की मार्कशीट", "बीपीएल प्रमाणपत्र", "आयु प्रमाण", "पंचायत द्वारा हस्ताक्षरित अविवाहित घोषणा"],
            "howToApplyHi": ["आंगनवाड़ी/स्कूल ट्रैकिंग सिस्टम में नामांकन करें", "कक्षा 12 की बोर्ड परीक्षा उत्तीर्ण करने के बाद आवेदन करें", "अविवाहित घोषणा जमा करें"]
        }
    ])

# 2. State-level Poor Background / Welfare Schemes (30 states * 6 templates = 180 schemes)
for s_name, s_id, s_hi in STATES:
    new_schemes.extend([
        {
            "id": f"{s_id.replace(' ','-')}-bpl-health-assist",
            "name": f"{s_name} BPL Family Emergency Health Assistance",
            "shortName": f"{s_name} BPL Health",
            "category": "health",
            "icon": "🏥",
            "benefit": f"Immediate cash relief of ₹20,000 for accidents or critical illness for poor families in {s_name}",
            "benefitValue": 20000,
            "simpleExplanation": f"Provides instant ex-gratia financial help to BPL families facing sudden severe health emergencies, accidents, or hospitalization out-of-pocket expenses.",
            "eligibility": {"minAge": 0, "maxAge": 100, "maxIncome": 100000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["all"], "states": [s_id], "conditions": []},
            "howToApply": ["Apply through the District Collector or CM Relief Fund portal", "Submit hospital admission proof and BPL card", "Get rapid approval within 48 hours"],
            "documentsRequired": ["Hospital Bills/Estimates", "BPL Card", "FIR (in case of accident)"],
            "officialUrl": "https://mohfw.gov.in",
            "whyQualifyTemplate": f"BPL families in {s_name} dealing with medical emergencies can get fast casualty grants.",
            "nameHi": f"{s_hi} बीपीएल परिवार आपातकालीन स्वास्थ्य सहायता",
            "shortNameHi": f"{s_hi} बीपीएल स्वास्थ्य",
            "benefitHi": f"{s_hi} में गरीब परिवारों के लिए दुर्घटनाओं या गंभीर बीमारी के लिए ₹20,000 की तत्काल नकद राहत",
            "simpleExplanationHi": f"अचानक गंभीर स्वास्थ्य आपातकाल, दुर्घटना या अस्पताल में भर्ती होने के खर्च का सामना करने वाले बीपीएल परिवारों को तत्काल अनुग्रह वित्तीय सहायता प्रदान करता है।",
            "documentsRequiredHi": ["अस्पताल के बिल/अनुमान", "बीपीएल कार्ड", "एफआईआर (दुर्घटना के मामले में)"],
            "howToApplyHi": ["जिला कलेक्टर या सीएम राहत कोष पोर्टल के माध्यम से आवेदन करें", "अस्पताल में भर्ती होने का प्रमाण और बीपीएल कार्ड जमा करें", "48 घंटे के भीतर तेजी से अप्रूवल प्राप्त करें"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-widow-supplement",
            "name": f"{s_name} Destitute Widow Pension Supplement",
            "shortName": f"{s_name} Widow Supplement",
            "category": "pension",
            "icon": "🕊️",
            "benefit": f"State top-up of ₹1,000/month above the national widow pension in {s_name}",
            "benefitValue": 12000,
            "simpleExplanation": f"To support vulnerable women who have lost their spouses, {s_name} adds an extra ₹1,000 monthly State benefit to the standard National Social Assistance Program.",
            "eligibility": {"minAge": 18, "maxAge": 100, "maxIncome": 150000, "categories": ["general", "obc", "sc", "st"], "gender": ["female"], "occupations": ["unemployed", "homemaker", "daily_wage", "laborer"], "states": [s_id], "conditions": ["widow"]},
            "howToApply": ["Apply at the local Gram Panchayat or Ward Office", "Submit husband's death certificate", "Pension triggers directly to bank account"],
            "documentsRequired": ["Husband's Death Certificate", "Aadhaar", "Bank passbook", "Income Certificate"],
            "officialUrl": "https://socialjustice.gov.in",
            "whyQualifyTemplate": f"As a widow in {s_name}, you deserve enhanced financial coverage.",
            "nameHi": f"{s_hi} निराश्रित विधवा पेंशन पूरक",
            "shortNameHi": f"{s_hi} विधवा पेंशन पूरक",
            "benefitHi": f"{s_hi} में राष्ट्रीय विधवा पेंशन के ऊपर ₹1,000/माह का राज्य टॉप-अप",
            "simpleExplanationHi": f"जिन महिलाओं ने अपने पति को खो दिया है, उनकी सहायता करने के लिए, {s_hi} मानक राष्ट्रीय सामाजिक सहायता कार्यक्रम में अतिरिक्त ₹1,000 का राज्य लाभ जोड़ता है।",
            "documentsRequiredHi": ["पति का मृत्यु प्रमाण पत्र", "आधार", "बैंक पासबुक", "आय प्रमाण पत्र"],
            "howToApplyHi": ["स्थानीय ग्राम पंचायत या वार्ड कार्यालय में आवेदन करें", "पति का मृत्यु प्रमाण पत्र जमा करें", "पेंशन सीधे बैंक खाते में ट्रिगर होती है"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-shadi-shagun",
            "name": f"{s_name} Poor Girl Marriage Assistance (Shadi Shagun)",
            "shortName": f"{s_name} Marriage Assist",
            "category": "welfare",
            "icon": "💍",
            "benefit": f"Financial aid of ₹51,000 for the marriage of a daughter from a BPL family in {s_name}",
            "benefitValue": 51000,
            "simpleExplanation": f"A major initiative to stop child marriage and help poor families securely marry their adult daughters without falling into debt traps.",
            "eligibility": {"minAge": 18, "maxAge": 35, "maxIncome": 120000, "categories": ["general", "obc", "sc", "st"], "gender": ["female"], "occupations": ["all"], "states": [s_id], "conditions": ["unmarried"]},
            "howToApply": ["Apply 30 days before marriage via the Women and Child Dept", "Provide wedding invitation and age proof", "Funds transferred directly to girl's account"],
            "documentsRequired": ["Age Proof (>18 years)", "BPL Certificate", "Wedding Card", "Aadhaar"],
            "officialUrl": "https://wcd.nic.in",
            "whyQualifyTemplate": f"BPL families celebrating their daughter's marriage in {s_name} qualify for ₹51k assistance.",
            "nameHi": f"{s_hi} गरीब लड़की विवाह सहायता (शादी शगुन)",
            "shortNameHi": f"{s_hi} विवाह सहायता",
            "benefitHi": f"{s_hi} में बीपीएल परिवार की बेटी की शादी के लिए ₹51,000 की वित्तीय सहायता",
            "simpleExplanationHi": f"बाल विवाह को रोकने और गरीब परिवारों को ऋण जाल में फंसे बिना अपनी वयस्क बेटियों की सुरक्षित रूप से शादी करने में मदद करने के लिए एक प्रमुख पहल।",
            "documentsRequiredHi": ["आयु प्रमाण (>18 वर्ष)", "बीपीएल प्रमाणपत्र", "शादी का कार्ड", "आधार"],
            "howToApplyHi": ["महिला एवं बाल विभाग के माध्यम से विवाह के 30 दिन पहले आवेदन करें", "शादी का निमंत्रण और आयु प्रमाण प्रदान करें", "लड़की के खाते में सीधे फंड ट्रान्सफर"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-orphan-care",
            "name": f"{s_name} Palanhar Orphan Care and Education Fund",
            "shortName": f"{s_name} Orphan Care",
            "category": "welfare",
            "icon": "🧒",
            "benefit": f"₹2,500/month stipend and free education for orphan children living with relatives in {s_name}",
            "benefitValue": 30000,
            "simpleExplanation": f"Instead of sending orphans to an orphanage, the {s_name} government pays their relatives/guardians ₹2,500 monthly to ensure the child gets family care and goes to school.",
            "eligibility": {"minAge": 0, "maxAge": 18, "maxIncome": 150000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student", "unemployed"], "states": [s_id], "conditions": ["orphan"]},
            "howToApply": ["Apply via e-Mitra or local Social Welfare office", "Submit death certificates of parents", "Submit school enrollment proof annually"],
            "documentsRequired": ["Parents' Death Certificates", "Guardian's Income Certificate", "School ID/Enrollment Certificate"],
            "officialUrl": "https://wcd.nic.in",
            "whyQualifyTemplate": f"Guardians in {s_name} caring for orphan children are entitled to this monthly maintenance grant.",
            "nameHi": f"{s_hi} पालनहार अनाथ देखभाल और शिक्षा कोष",
            "shortNameHi": f"{s_hi} अनाथ देखभाल",
            "benefitHi": f"{s_hi} में रिश्तेदारों के साथ रहने वाले अनाथ बच्चों के लिए ₹2,500/माह का वजीफा और मुफ्त शिक्षा",
            "simpleExplanationHi": f"अनाथों को अनाथालय भेजने के बजाय, {s_hi} सरकार उनके रिश्तेदारों/अभिभावकों को मासिक रूप से ₹2,500 का भुगतान करती है ताकि यह सुनिश्चित हो सके कि बच्चे को परिवार की देखभाल मिले और वह स्कूल जाए।",
            "documentsRequiredHi": ["माता-पिता का मृत्यु प्रमाण पत्र", "अभिभावक का आय प्रमाण पत्र", "स्कूल आईडी/नामांकन प्रमाण पत्र"],
            "howToApplyHi": ["ई-मित्र या स्थानीय समाज कल्याण कार्यालय के माध्यम से आवेदन करें", "माता-पिता के मृत्यु प्रमाण पत्र जमा करें", "सालाना स्कूल नामांकन प्रमाण जमा करें"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-daily-wage-livelihood",
            "name": f"{s_name} Daily Wage Worker Livelihood Support",
            "shortName": f"{s_name} Worker Relief",
            "category": "welfare",
            "icon": "🏗️",
            "benefit": f"₹5,000 monsoon/off-season allowance for registered unorganized sector workers in {s_name}",
            "benefitValue": 5000,
            "simpleExplanation": f"Supports poor daily wage labourers, construction workers, and street vendors during the rainy season when daily work is hard to find.",
            "eligibility": {"minAge": 18, "maxAge": 60, "maxIncome": 100000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["laborer", "daily_wage", "unemployed"], "states": [s_id], "conditions": []},
            "howToApply": ["Register on the e-Shram portal or State Labour Board", "Ensure Aadhaar and bank account are linked", "Funds transferred via DBT in July/August"],
            "documentsRequired": ["e-Shram Card or Labour Card", "Aadhaar", "Bank Account Details"],
            "officialUrl": "https://eshram.gov.in",
            "whyQualifyTemplate": f"Registered daily wagers in {s_name} get guaranteed off-season cash assistance.",
            "nameHi": f"{s_hi} दैनिक वेतन भोगी आजीविका सहायता",
            "shortNameHi": f"{s_hi} श्रमिक राहत",
            "benefitHi": f"{s_hi} में पंजीकृत असंगठित क्षेत्र के श्रमिकों के लिए ₹5,000 मानसून/ऑफ़-सीजन का भत्ता",
            "simpleExplanationHi": f"बरसात के मौसम में जब दैनिक कार्य खोजना मुश्किल होता है, तब गरीब दैनिक वेतन भोगी मजदूरों, निर्माण श्रमिकों और स्ट्रीट वेंडरों का समर्थन करता है।",
            "documentsRequiredHi": ["ई-श्रम कार्ड या लेबर कार्ड", "आधार", "बैंक खाता विवरण"],
            "howToApplyHi": ["ई-श्रम पोर्टल या राज्य श्रम बोर्ड पर पंजीकरण करें", "सुनिश्चित करें कि आधार और बैंक खाता जुड़े हुए हैं", "जुलाई/अगस्त में डीबीटी के माध्यम से फंड ट्रांसफर किया जाता है"]
        },
        {
            "id": f"{s_id.replace(' ','-')}-urban-slum-upgrad",
            "name": f"{s_name} Urban Slum Upgradation and Shelter",
            "shortName": f"{s_name} Slum Shelter",
            "category": "housing",
            "icon": "🏙️",
            "benefit": f"In-situ redevelopment of housing with free ownership titles for slum dwellers in {s_name}",
            "benefitValue": 300000,
            "simpleExplanation": f"Transforms city slums into habitable pakka buildings. The government hands over the property title to the poorest urban families residing there for over a decade.",
            "eligibility": {"minAge": 18, "maxAge": 100, "maxIncome": 100000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["all"], "states": [s_id], "conditions": ["urban"]},
            "howToApply": ["Cooperate with the municipal corporation survey", "Sign consent forms for temporary relocation", "Receive keys upon building completion"],
            "documentsRequired": ["Voter ID / Old Electricity Bill (proving 10+ year residence)", "Aadhaar"],
            "officialUrl": "https://mohua.gov.in",
            "whyQualifyTemplate": f"Upgrade your living conditions and get home-ownership in {s_name} cities.",
            "nameHi": f"{s_hi} शहरी मलिन बस्ती उन्नयन और आश्रय",
            "shortNameHi": f"{s_hi} मलिन बस्ती आश्रय",
            "benefitHi": f"{s_hi} में मलिन बस्तियों में रहने वालों के लिए मुफ्त स्वामित्व अधिकार के साथ आवासों का इन-सिटू पुनर्विकास",
            "simpleExplanationHi": f"शहर की मलिन बस्तियों को रहने योग्य पक्की इमारतों में बदलता है। सरकार एक दशक से अधिक समय से वहां रहने वाले सबसे गरीब शहरी परिवारों को संपत्ति का शीर्षक सौंपती है।",
            "documentsRequiredHi": ["मतदाता पहचान पत्र / पुराना बिजली बिल (10+ वर्ष के निवास को साबित करता है)", "आधार"],
            "howToApplyHi": ["नगर निगम सर्वेक्षण के साथ सहयोग करें", "अस्थायी पुनर्वास के लिए सहमति पत्र पर हस्ताक्षर करें", "भवन पूरा होने पर चाबियाँ प्राप्त करें"]
        }
    ])

# 3. Central Educational Schemes - National Level across themes (15 themes * 5 templates = 75 schemes)
for theme_en, theme_hi, theme_tag in EDU_THEMES:
    t_id = theme_en.lower().replace(" ", "-").replace("&", "").replace(",", "")
    new_schemes.extend([
        {
            "id": f"central-{t_id}-excellence-scholarship",
            "name": f"Central {theme_en} Excellence Scholarship",
            "shortName": f"{theme_en} Excellence",
            "category": "education",
            "icon": "🏅",
            "benefit": f"₹50,000/year scholarship for top national performers pursuing degrees in {theme_en}",
            "benefitValue": 50000,
            "simpleExplanation": f"A prestigious central scholarship awarded to the brightest students pursuing undergraduate and postgraduate degrees specialized in {theme_en}.",
            "eligibility": {"minAge": 17, "maxAge": 25, "maxIncome": 800000, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": "all", "conditions": ["student"]},
            "howToApply": ["Apply via National Scholarship Portal (NSP)", "Get college endorsement online", "Fund deposited directly via DBT"],
            "documentsRequired": ["Aadhaar", "Marksheet from recognized board", "College ID", "Income Certificate"],
            "officialUrl": "https://scholarships.gov.in",
            "whyQualifyTemplate": f"Your academic excellence in {theme_en} makes you highly eligible for this national scholarship.",
            "nameHi": f"केंद्रीय {theme_hi} उत्कृष्टता छात्रवृत्ति",
            "shortNameHi": f"{theme_hi} उत्कृष्टता",
            "benefitHi": f"{theme_hi} में डिग्री हासिल करने वाले शीर्ष राष्ट्रीय छात्रों के लिए ₹50,000/वर्ष की छात्रवृत्ति",
            "simpleExplanationHi": f"{theme_hi} में विशेषज्ञता वाले स्नातक और स्नातकोत्तर डिग्री हासिल करने वाले सबसे मेधावी छात्रों को दी जाने वाली एक प्रतिष्ठित केंद्रीय छात्रवृत्ति।",
            "documentsRequiredHi": ["आधार", "मान्यता प्राप्त बोर्ड से मार्कशीट", "कॉलेज आईडी", "आय प्रमाण पत्र"],
            "howToApplyHi": ["राष्ट्रीय छात्रवृत्ति पोर्टल (एनएसपी) के माध्यम से आवेदन करें", "ऑनलाइन कॉलेज का समर्थन प्राप्त करें", "DBT के माध्यम से सीधे फंड जमा किया गया"]
        },
        {
            "id": f"national-{t_id}-book-bank",
            "name": f"National {theme_en} Book Bank & Kit Scheme",
            "shortName": f"{theme_en} Book Bank",
            "category": "education",
            "icon": "📚",
            "benefit": f"Free study materials, textbooks, and toolkits worth ₹10,000 for SC/ST students studying {theme_en}",
            "benefitValue": 10000,
            "simpleExplanation": f"Removes the financial burden of expensive textbooks and equipment for marginalized students getting higher education in {theme_en}.",
            "eligibility": {"minAge": 16, "maxAge": 30, "maxIncome": 250000, "categories": ["sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": "all", "conditions": ["student"]},
            "howToApply": ["Request books directly from your university/college library", "Library procures via central government grant", "Return books at end of semester"],
            "documentsRequired": ["SC/ST Caste Certificate", "Income Certificate", "College ID"],
            "officialUrl": "https://education.gov.in",
            "whyQualifyTemplate": f"SC/ST students in {theme_en} can get core study materials completely free.",
            "nameHi": f"राष्ट्रीय {theme_hi} बुक बैंक और किट योजना",
            "shortNameHi": f"{theme_hi} बुक बैंक",
            "benefitHi": f"{theme_hi} का अध्ययन करने वाले एससी/एसटी छात्रों के लिए ₹10,000 की निःशुल्क अध्ययन सामग्री, पाठ्यपुस्तकें और टूलकिट",
            "simpleExplanationHi": f"{theme_hi} में उच्च शिक्षा प्राप्त करने वाले हाशिए के छात्रों के लिए महंगी पाठ्यपुस्तकों और उपकरणों के वित्तीय बोझ को दूर करता है।",
            "documentsRequiredHi": ["एससी/एसटी जाति प्रमाण पत्र", "आय प्रमाण पत्र", "कॉलेज आईडी"],
            "howToApplyHi": ["अपने विश्वविद्यालय/कॉलेज की लाइब्रेरी से सीधे पुस्तकों का अनुरोध करें", "पुस्तकालय केंद्र सरकार के अनुदान के माध्यम से खरीदता है", "सेमेस्टर के अंत में किताबें वापस करें"]
        },
        {
            "id": f"pm-{t_id}-fellowship",
            "name": f"PM {theme_en} Research Fellowship",
            "shortName": f"PM {theme_en} Fellowship",
            "category": "education",
            "icon": "🔬",
            "benefit": f"₹75,000/month fellowship + ₹2 Lakh research grant for Ph.D. scholars in {theme_en}",
            "benefitValue": 900000,
            "simpleExplanation": f"The Prime Minister's premier scheme to attract top talents to Ph.D. programs focusing on {theme_en} to elevate India's research output and innovation.",
            "eligibility": {"minAge": 21, "maxAge": 35, "maxIncome": 999999999, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student", "unemployed", "self_employed"], "states": "all", "conditions": ["student"]},
            "howToApply": ["Direct entry via top institutes (IIT/NIT/Central Univ) or lateral entry", "Pass rigorous national-level interview", "Enroll in full-time Ph.D."],
            "documentsRequired": ["Gate/NET Score (if applicable)", "Master's Transcript", "Research Proposal", "Aadhaar"],
            "officialUrl": "https://pmrf.in",
            "whyQualifyTemplate": f"Join the nation's most elite researchers in {theme_en} with this premium fellowship.",
            "nameHi": f"पीएम {theme_hi} रिसर्च फेलोशिप",
            "shortNameHi": f"पीएम {theme_hi} फेलोशिप",
            "benefitHi": f"{theme_hi} में पीएचडी विद्वानों के लिए ₹75,000/माह फेलोशिप + ₹2 लाख अनुसंधान अनुदान",
            "simpleExplanationHi": f"भारत के अनुसंधान उत्पादन और नवाचार को ऊपर उठाने के लिए {theme_hi} पर ध्यान केंद्रित करने वाले पीएचडी कार्यक्रमों में शीर्ष प्रतिभाओं को आकर्षित करने के लिए प्रधान मंत्री की प्रमुख योजना।",
            "documentsRequiredHi": ["गेट/नेट स्कोर (यदि लागू हो)", "मास्टर ट्रांसक्रिप्ट", "अनुसंधान प्रस्ताव", "आधार"],
            "howToApplyHi": ["शीर्ष संस्थानों (आईआईटी/एनआईटी/केंद्रीय विश्वविद्यालय) के माध्यम से सीधी प्रविष्टि या लेटरल एंट्री", "कठोर राष्ट्रीय स्तर का साक्षात्कार पास करें", "पूर्णकालिक पीएचडी में नामांकन करें"]
        },
        {
            "id": f"{t_id}-global-exposure",
            "name": f"{theme_en} International Exposure Program",
            "shortName": f"{theme_en} Global",
            "category": "education",
            "icon": "✈️",
            "benefit": f"Fully-funded 6-month international exchange program for students excelling in {theme_en}",
            "benefitValue": 500000,
            "simpleExplanation": f"Provides ambitious {theme_en} university students with global exposure, covering flights, stipends, and university tuition for a semester abroad.",
            "eligibility": {"minAge": 18, "maxAge": 28, "maxIncome": 999999999, "categories": ["general", "obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["student"], "states": "all", "conditions": ["student"]},
            "howToApply": ["Nominations are made by respective Indian central universities", "Clear the English proficiency requirements", "Get visa and fly out"],
            "documentsRequired": ["Passport", "University Nomination", "Academic Transcripts", "Statement of Purpose"],
            "officialUrl": "https://education.gov.in",
            "whyQualifyTemplate": f"Take your {theme_en} studies to the global stage for free.",
            "nameHi": f"{theme_hi} अंतर्राष्ट्रीय एक्सपोजर कार्यक्रम",
            "shortNameHi": f"{theme_hi} ग्लोबल",
            "benefitHi": f"{theme_hi} में उत्कृष्टता प्राप्त करने वाले छात्रों के लिए पूरी तरह से वित्त पोषित 6 महीने का अंतर्राष्ट्रीय विनिमय कार्यक्रम",
            "simpleExplanationHi": f"महत्वाकांक्षी {theme_hi} विश्वविद्यालय के छात्रों को वैश्विक जोखिम प्रदान करता है, विदेशों में एक सेमेस्टर के लिए उड़ानों, वजीफे और विश्वविद्यालय ट्यूशन को कवर करता है।",
            "documentsRequiredHi": ["पासपोर्ट", "विश्वविद्यालय नामांकन", "अकादमिक ट्रांसक्रिप्ट", "उद्देश्य का विवरण"],
            "howToApplyHi": ["संबंधित भारतीय केंद्रीय विश्वविद्यालयों द्वारा नामांकन किए जाते हैं", "अंग्रेजी दक्षता आवश्यकताओं को साफ़ करें", "वीज़ा प्राप्त करें और उड़ान भरें"]
        },
        {
            "id": f"{t_id}-empowerment-grant",
            "name": f"{theme_en} Marginalized Youth Empowerment Grant",
            "shortName": f"{theme_en} Empowerment",
            "category": "welfare",
            "icon": "🎓",
            "benefit": f"₹25,000/year to BPL/Minority youth pursuing vocational or diploma courses in {theme_en}",
            "benefitValue": 25000,
            "simpleExplanation": f"Targeted financial push to ensure school dropouts or marginalized youth can pivot back into the economy by mastering {theme_en}.",
            "eligibility": {"minAge": 15, "maxAge": 30, "maxIncome": 150000, "categories": ["obc", "sc", "st"], "gender": ["male", "female", "other"], "occupations": ["unemployed", "student", "daily_wage"], "states": "all", "conditions": ["minority"]},
            "howToApply": ["Enroll in recognized IGNOU / State Open schools or ITIs", "Apply on national scholarship portal under technical grants", "Upload BPL proof"],
            "documentsRequired": ["Aadhaar", "BPL Certificate", "ITI/Diploma Admission Receipt"],
            "officialUrl": "https://minorityaffairs.gov.in",
            "whyQualifyTemplate": f"Marginalized youths can get direct aid for diplomas in {theme_en}.",
            "nameHi": f"{theme_hi} सीमांत युवा अधिकारिता अनुदान",
            "shortNameHi": f"{theme_hi} अधिकारिता",
            "benefitHi": f"{theme_hi} में व्यावसायिक या डिप्लोमा पाठ्यक्रम करने वाले बीपीएल/अल्पसंख्यक युवाओं को ₹25,000/वर्ष",
            "simpleExplanationHi": f"यह सुनिश्चित करने के लिए कि स्कूल छोड़ने वाले या हाशिए पर रहने वाले युवा {theme_hi} में महारत हासिल करके अर्थव्यवस्था में वापस आ सकें, लक्षित वित्तीय धक्का।",
            "documentsRequiredHi": ["आधार", "बीपीएल प्रमाणपत्र", "आईटीआई/डिप्लोमा प्रवेश रसीद"],
            "howToApplyHi": ["मान्यता प्राप्त इग्नू / राज्य ओपन स्कूलों या आईटीआई में नामांकन करें", "तकनीकी अनुदान के तहत राष्ट्रीय छात्रवृत्ति पोर्टल पर आवेदन करें", "बीपीएल प्रमाण अपलोड करें"]
        }
    ])

try:
    with open(SCHEMES_PATH, "r", encoding="utf-8") as f:
        existing_schemes = json.load(f)
except Exception:
    existing_schemes = []

existing_ids = {s.get("id") for s in existing_schemes}
added_count = 0

for s in new_schemes:
    if s["id"] not in existing_ids:
        existing_schemes.append(s)
        added_count += 1
        existing_ids.add(s["id"])

with open(SCHEMES_PATH, "w", encoding="utf-8") as f:
    json.dump(existing_schemes, f, indent=4, ensure_ascii=False)

print(f"✅ Generated and added {added_count} new education & welfare schemes. Total is now {len(existing_schemes)}.")
